### Dot product (vector - vector)

In [3]:
import numpy as np

def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]

    return result

u = np.array([1,2,3])
v = np.array([3,4,5])

print(vector_vector_multiplication(u,v))

print(u.dot(v))

26.0
26


#### Matrix-vector multiplication

In [ ]:
def matrix_vector_multiplication(u, v):
    assert u.shape[1] == v.shape[0]

    n = u.shape[0]

    dot_p = []

    for i in range(n):
        dot_p.append(u[i].dot(v))

    return dot_p

u = np.array([[1,2,3], [2,6,7], [7,8,3]])
v = np.array([3,4,5])

print(matrix_vector_multiplication(u, v))
np.matmul(u, v).sum()
sum(u.dot(v))


[np.int64(26), np.int64(65), np.int64(68)]


In [48]:
def matrix_matrix_multiplication(u, v):

    assert u.shape[0] == v.shape[1] 

    v = np.transpose(v)
    n = v.shape[0]
    result = []

    for i in range(n):
        result.append(matrix_vector_multiplication(u, v[i]))

    return np.transpose(result)


u = np.array([[2,4,5,6], [1,2,1,2], [3,1,2,1]])
v = np.array([[1,1,2], [1,0.5,1], [0,2,1], [2,1,0]])

result = matrix_matrix_multiplication(u ,v)
np.array(result)

array([[18. , 20. , 13. ],
       [ 7. ,  6. ,  5. ],
       [ 6. ,  8.5,  9. ]])

In [52]:
I = np.eye(3)
v.dot(I)

array([[1. , 1. , 2. ],
       [1. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [55]:
Vs = v[[0,1,2]]
Vs_inv = np.linalg.inv(Vs)

Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])