In [2]:
import numpy as np

### Creating Arrays

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.full(5,3)

array([3, 3, 3, 3, 3])

In [9]:
a = np.array([1,4,7,8,3])
a

a[2]
a[2] = 10
a

array([ 1,  4, 10,  8,  3])

In [11]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Creating Multi-Dementional Arrays

In [55]:
a = np.zeros((5,2))
a.shape
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [53]:
n = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(n[2])
n[1][2]
n[0,0]
n[:,0]

[7 8 9]


array([1, 4, 7])

### Randomly Generated Arrays

In [26]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [25]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [31]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(2,5))


array([[40, 15, 72, 22, 43],
       [82, 75,  7, 34, 49]])

### Element-wise Operations

In [ ]:
a = np.arange(5)
b = np.arange(5)

In [41]:
a + b * 20

array([ 0, 21, 42, 63, 84])

### Comparison Operations

In [42]:
a = np.arange(5)
b = np.arange(5)
b = b + 1

In [46]:
b >= 2

array([False,  True,  True,  True,  True])

In [49]:
b[b > a]
a[a < b]

array([0, 1, 2, 3, 4])

### Summarising Operations

In [52]:
a.min()
a.max()
a.sum()

np.int64(10)